language: python
python:
  - "2.7"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 4.2.0
  - make build
  - cp src/sgd/frontend/default_config.py src/sgd/frontend/config.py
script: make tests
